services:
  - type: web
    name: predictive-maintenance-system
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
